import Identifier from "domain/interfaces/identifier"
import Annotation from "domain/commonObjects/annotation"
import IPeriod from "domain/commonObjects/period"

enum statusReason {
  "Procedure contraindicated",
  "Nitrate contraindicated",
  "Diuretic contraindicated",
  "Lipid lowering therapy contraindicated",
  "Angiotensin II receptor antagonists contraindicated",
  "Clopidogrel contraindicated",
  "Metformin contraindicated",
  "Hepatitis B vaccination contraindicated",
  "Procedure discontinued",
  "Oral steroids stopped"
}

enum category {
  "Psychiatry procedure or service",
  "Counseling",
  "Education",
  "Surgical procedure (procedure)",
  "Diagnostic procedure",
  "Chiropractic manipulation",
  "Social service procedure (procedure)"
}

enum code {
    "Procedure",
   	"Excision of lesion of patella",
   	"Removable appliance therapy",
   	"Thoracoscopic partial lobectomy of lung",
   	"Retrobulbar injection of therapeutic agent",
   	"Hand microscope examination of skin",
   	"Percutaneous implantation of neurostimulator electrodes into neuromuscular component",
   	"Arthrotomy of wrist joint with exploration and biopsy",
   	"Excision of tumor from shoulder area, deep, intramuscular",
   	"Repair of nonunion of metatarsal with bone graft",
   	"Cystourethroscopy with resection of ureterocele",
   	"Removal of foreign body of tendon and/or tendon sheath (procedure)",
   	"Behavioral therapy",
   	"Special potency disk identification, vancomycin test",
   	"Harrison-Richardson operation on vagina",
   	"Anastomosis of rectum",
   	"Excision of lesion of artery",
   	"Mold to yeast conversion test",
   	"Miller operation, urethrovesical suspension",
   	"Replacement of cerebral ventricular tube",
   	"Division of nerve ganglion",
   	"Percutaneous aspiration of renal pelvis",
   	"Anal fistulectomy, multiple",
   	"Incision and drainage of vulva",
   	"Excisional biopsy of joint structure of spine",
   	"Nonexcisional destruction of cyst of ciliary body",
   	"Echography of kidney ",
}

enum performerFunction {
    "Healthcare professional",
   	"Specialized surgeon",
   	"Radiation therapist",
   	"Chiropractor",
   	"Dental assistant",
   	"Auxiliary nurse",
   	"Specialized nurse",
   	"Hospital administrator",
   	"Plastic surgeon",
  	"Neuropathologist",
  	"Nephrologist",
  	"Obstetrician",
  	"School dental assistant",
  	"Medical microbiologist",
  	"Cardiologist",
  	"Dermatologist",
  	"Laboratory hematologist",
  	"Gerodontist",
  	"Removable prosthodontist",
  	"Specialized dentist",
  	"Neuropsychiatrist",
  	"Medical assistant",
  	"Orthopedic surgeon",
  	"Thoracic surgeon",
  	"Community health physician",
  	"Physical medicine specialist",
  	"Urologist",
  	"Electroencephalography specialist",
  	"Dental hygienist",
  	"Public health nurse",
  	"Optometrist",
  	"Neonatologist",
  	"Medical biochemist",
  	"Physiotherapist",
  	"Periodontist",
  	"Orthodontist",
  	"Internal medicine specialist",
  	"Dietitian (general)",
  	"Hematologist",
  	"Interpreter",
  	"Respiratory disease specialist",
  	"Medical X-ray technician",
  	"Occupational health nurse",
  	"Pharmaceutical assistant",
  	"Masseur",
  	"Rheumatologist",
  	"Neurosurgeon",
  	"Sanitarian",
  	"Pharmacist",
  	"Philologist",
  	"Dispensing optician",
  	"Oral surgeon",
  	"Endodontist",
  	"Faith healer",
  	"Neurologist",
  	"Public health physician",
  	"Medical record administrator",
  	"Cardiovascular surgeon",
  	"Fixed prosthodontist",
  	"General physician",
  	"Orthopedic technician",
  	"Dental prosthesis maker and repairer",
  	"Psychologist",
  	"Public health nutritionist",
  	"Medical pathologist",
  	"Laboratory medicine specialist",
  	"Otorhinolaryngologist",
  	"Endocrinologist",
  	"Family medicine specialist",
  	"Clinical immunologist",
  	"Oral pathologist",
  	"Radiologist",
  	"Public health dentist",
  	"Prosthodontist",
  	"Specialized physician",
  	"Gastroenterologist",
  	"Nursing aid",
  	"Professional midwife",
  	"Practical aid (pharmacy)",
  	"Osteopath",
  	"Infectious disease specialist",
  	"General surgeon",
  	"Diagnostic radiologist",
  	"Auxiliary midwife",
  	"Translator",
  	"Occupational therapist",
  	"Psychiatrist",
  	"Nuclear medicine specialist",
  	"Clinical pathologist",
  	"Pediatrician",
  	"Anatomic pathologist",
  	"Gynecologist",
  	"General pathologist",
  	"Anesthesiologist",
  	"Pedodontist",
  	"Geriatrics specialist",
   	"Dentist",
   	"Dietician AND/OR public health nutritionist",
   	"Professional nurse",
   	"Nursing personnel",
   	"Midwifery personnel",
   	"Physiotherapist AND/OR occupational therapist",
   	"Philologist, translator AND/OR interpreter",
   	"Medical practitioner",
   	"Medical administrator - national",
   	"Consultant physician",
   	"Consultant surgeon",
   	"Consultant gynecology and obstetrics",
   	"Hospital registrar",
   	"House officer",
   	"Occupational physician",
   	"Clinical medical officer",
   	"Medical practitioner - teaching",
   	"Dental administrator",
   	"Dental consultant",
   	"Dental general practitioner",
   	"Dental practitioner - teaching",
   	"Nurse administrator - national",
   	"Nursing officer - region",
   	"Nursing officer - district",
   	"Nursing administrator - professional body",
   	"Nursing officer - division",
   	"Nurse education director",
   	"Occupational health nursing officer",
}

enum outcome {
  "Successful (qualifier value)",
 	"Unsuccessful (qualifier value)",
  "Partially successful (qualifier value)",
}

enum followUp {
  "Change of dressing",
	"Removal of suture",
 	"Removal of drain",
	"Removal of staples",
 	"Removal of ligature",
 	"Cardiopulmonary exercise test (procedure)",
 	"Scar tissue massage",
 	"Suction drainage",
 	"Diabetes medication review (procedure)",
 	"Cytopathology, review of bronchioalveolar lavage specimen",

}

enum usedCode {
"Device",
"Spine board",
"Bone plate",
"Air receiver",
"Atomizer",
"Epilator",
"Bicycle ergometer",
"Mechanical power press",
"Diagnostic implant",
"Air filter",
"Linen cloth",
"Brush",
"Treadmill",
"Emesis basin",
"Plastic mold",
"Surgical drill",
"Toboggan",
"Silk cloth",
"Dike",
"Endotracheal tube cuff",
"Breast prosthesis",
"Nail file",
"Breath analyzer",
"Glass eye",
"Intra-aortic balloon catheter",
"Tent",
"Artificial liver",
"Endoscopic camera",
"Hair cloth",
"Metal device",
"Adhesive strip",
"Patient scale",
"Physiologic monitoring system",
"Bed sheet",
"Hearing aid",
"T-tube",
"Microwave oven",
"Protective clothing material",
"Lithotripter",
"Radiographic-fluoroscopic unit",
"Probe",
"Crib",
"Stabilizing appliance",
"Hydrocephalic shunt catheter",
"Three-wheeled all-terrain vehicle",
"Fogarty catheter",
"Denture",
"Crane",
"Adhesive",
"Band saw",
"Bile collection bag",
"Jail",
"Intramedullary rod",
"Blood electrolyte analyzer",
"Mortising machine",
"Protective shield",
"Ventricular intracranial catheter",
"Support",
"Feeding catheter",
"Bobsled",
"Elastic bandage",
"Dermatotome",
"Mycoplasma pulmonis antibody test kit",
"Cargo handling gear",
"Needle guide",
"Electrostimulating analgesia unit",
"Toeboard",
"Industrial saw",
"Radiographic-therapeutic unit",
"Vein stripper",
}


export default interface Procedure {
  identifier :Identifier[], // External Identifiers for this procedure
  status : "<code>", // R!  preparation | in-progress | not-done | on-hold | stopped | completed | entered-in-error | unknown
  statusReason : statusReason, // Reason for current status
  category : category, // Classification of the procedure
  code : code, // Identification of the procedure
  performedPeriod :  IPeriod,
  performer : [{ // The people who performed the procedure
    function : performerFunction, // Type of performance
    // "actor" : { Reference(Device|Organization|Patient|Practitioner|
    // PractitionerRole|RelatedPerson) }, // R!  The reference to the practitioner
    // "onBehalfOf" : { Reference(Organization) } // Organization the device or practitioner was acting for
  }],
  outcome : outcome, // The result of procedure
  followUp : followUp, // Instructions for follow up
  note : Annotation[], // Additional information about the procedure
  usedCode : usedCode[] // Coded items used during the procedure
}